package ua.edu.catalog.persistence;

import java.sql.*;

public final class Db {
    private static final String URL = "jdbc:h2:file:./data/catalog;AUTO_SERVER=TRUE";

    private Db() {}

    public static Connection get() throws SQLException {
        return DriverManager.getConnection(URL, "sa", "");
    }

    public static void init() {
        try (Connection c = get(); Statement s = c.createStatement()) {
            s.executeUpdate("""
                CREATE TABLE IF NOT EXISTS books(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    author VARCHAR(255) NOT NULL,
                    pub_year INT NOT NULL
                )
                """);
            s.executeUpdate("""
                CREATE TABLE IF NOT EXISTS comments(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    book_id BIGINT NOT NULL,
                    author VARCHAR(64) NOT NULL,
                    text VARCHAR(1000) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    CONSTRAINT fk_comment_book FOREIGN KEY(book_id) REFERENCES books(id)
                )
                """);

            try (ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM books")) {
                rs.next();
                if (rs.getLong(1) == 0) {
                    s.executeUpdate("""
                        INSERT INTO books(title, author, pub_year) VALUES
                        ('1984', 'George Orwell', 1949),
                        ('Clean Code', 'Robert C. Martin', 2008),
                        ('Effective Java', 'Joshua Bloch', 2018),
                        ('Refactoring', 'Martin Fowler', 2018),
                        ('Design Patterns', 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides', 1994),
                        ('The Pragmatic Programmer', 'Andrew Hunt, David Thomas', 1999)
                        """);
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot initialize database", e);
        }
    }
}
